blank_issues_enabled: false
contact_links:
  - name: English Support Forum @ kodi.tv
    url: https://forum.kodi.tv/showthread.php?tid=349255
    about: For questions in English use kodi.tv Forum.
  - name: German Support Forum @ kodinerds.net
    url: https://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/
    about: For questions in German use kodinerds.net Forum.
